version: '3'
services:
  child-first:
    build:
      context: ./child-first-ms-bp
#    environment:
#      - ENV_VARIABLE_NAME_1=value1
    depends_on:
      - rabbitmq
  child-second:
    build:
      context: ./child-second-ms-bp
#    environment:
#      - ENV_VARIABLE_NAME_2=value2
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:latest